### ISSUE TITLE
Is Co-Mixup actually slower than PuzzleMix only 1.04 times?

### ISSUE THREAD

**Issue by minhlong94** [snu-mllab/Co-Mixup#1]
From the paper, it is stated that 
> Note that Co-Mixup requires saliency computation, and when we compare the algorithm with Puzzle Mix, which performs the same saliency computation, Co-Mixup is only slower about 1.04 times.

But from the [log.txt](https://github.com/snu-mllab/Co-Mixup/blob/main/checkpoint/cifar100_preactresnet18_eph300_comixup/log.txt) off Co-Mixup, the start time and end time (at epoch 100) are:
```
==>>[2020-10-12 04:53:43] [Epoch=000/300]
==>>[2020-10-12 09:51:36] [Epoch=100/300]
```

And from the [log.txt](https://github.com/snu-mllab/PuzzleMix/blob/master/checkpoint/preactresnet18/log.txt) of PuzzleMix, the start and end time (also at epoch 100) are:
```
==>>[2020-01-27 05:40:49] [Epoch=000/1200]
==>>[2020-01-27 08:00:22] [Epoch=100/1200]
```

We can calculate that Co-mixup requires `17,873` seconds and PuzzleMix requires `8,373` seconds, so for 100 epochs, Co-mixup runtime is almost double PuzzleMix. How can this be 1.04 times slower than PuzzleMix, or it just compares the optimization algorithm with PuzzleMix only?

**Comment by Janghyun1230** [comment]
Hello! It depends on the dataset and model. In the paper, we compare the speed on ImageNet with ResNet-50, where network computation takes much longer time than CIFAR experiments. Note, the computing cost of data augmentation remains similar (compared to CIFAR), because we down-sample images to the specific size regardless of the original image size when performing optimization.  

As you noted, in CIFAR experiments, Co-Mixup is much slower than PuzzleMix.

**Comment by minhlong94** [comment]
Thanks for your comment! I will close the issue.

**Comment by minhlong94** [comment]
Hello,
I am working on the same direction as PuzzleMix and Co-Mixup. May I ask what devices are used to train CIFAR-100, both Co-Mixup and PuzzleMix? In Co-Mixup paper, for ImageNet it was 4 NVIDIA RTX 2080 Ti GPUs, but I can't find CIFAR-100 case.

**Comment by Janghyun1230** [comment]
Hello! For Cifar-100 experiments, we used 1 Titan-XP or 1 RTX2080-Ti.

**Comment by minhlong94** [comment]
Thanks for your fast reply! I'll close the issue accordingly.
