### ISSUE TITLE
Training Curve/Log of ImageNet experiments?

### ISSUE THREAD

**Issue by minhlong94** [snu-mllab/Co-Mixup#2]
Hello,

I am trying to reproduce the ImageNet experiments, however, the runtime took longer than I expected. Since the training protocol is new, I want to compare the training curve, as well as runtime. Can you also release the log.txt, or the plot of ImageNet experiments, as well as the (expected) runtime? Preferably, I would like to have PuzzleMix's too.

Warmly,
Long

**Comment by Janghyun1230** [comment]
Hi, Long

Currently, I only have trained checkpoints and I do not have a training curve for ImageNet experiments. (For CIFAR-100, you can check the log in the [checkpoint folder](https://github.com/snu-mllab/Co-Mixup/tree/main/checkpoint/cifar100_preactresnet18_eph300_comixup)). 

I just tested the code and measure the process times. To measure the processing time per batch, I modified the print_freq argument as 1 ( ./configs/comix/*.yml file). However, I found that **apex** occurs some problem with my updated GPU driver (especially the amp.scale_loss function in main_fast_ddp.py and this becomes the bottleneck of the process). So I turn off the automatic loss scaling (i.e., amp.scale_loss) and replace it with naive backward function. 

After some iterations, the processing time per batch is as follows.
Environment:
- CPU: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (total 20 cores)
- GPU: 4 NVIDIA TITAN Xp 

Co-Mixup
![comix](https://user-images.githubusercontent.com/30120035/135247079-b2e98674-9cd3-4161-94fc-5313ffe707f5.PNG)

Vanilla
![vanilla](https://user-images.githubusercontent.com/30120035/135247156-20a41e41-2ae0-4cf3-bc60-286da2b6e35e.PNG)

From the log above, the Co-Mixup takes about 1.3s and Vanilla training takes about 0.43s per batch. So the Co-Mixup on ImageNet is slower than Vanilla training about 3 times. This is due to the additional forward-backward pass for saliency calculation and optimization step for Co-Mixup, and reducing the processing time is one of the remained goals. 

If your relative Co-Mixup training time is much slower than my case, then I suspect apex which has many dependency problems. For more dependency-free training code, please refer to [here](https://github.com/snu-mllab/PuzzleMix/tree/master/cutmix), which trains ResNet without apex. 

I hope this helps.

Best,
Jang-Hyun

**Comment by Janghyun1230** [comment]
Hi, Long

Currently, I only have trained checkpoints and I do not have a training curve for ImageNet experiments. (For CIFAR-100, you can check the log in the checkpoint folder). 

I just tested the code and measure the process times. To measure the processing time per batch, I modified the print_freq argument as 1 ( ./configs/comix/*.yml file). However, I found that **apex** occurs some problem with my updated GPU driver (especially the amp.scale_loss function in main_fast_ddp.py and this becomes the bottleneck of the process). So I turn off the automatic loss scaling and replace it with naive backward function. 

After some iterations, the processing time per batch is as follows.
Environment:
- CPU: Intel(R) Xeon(R) CPU E5-2650 v4 @ 2.20GHz (total 20 cores)
- GPU: 4 NVIDIA TITAN Xp 

Co-Mixup
![comix](https://user-images.githubusercontent.com/30120035/135247079-b2e98674-9cd3-4161-94fc-5313ffe707f5.PNG)

Vanilla
![vanilla](https://user-images.githubusercontent.com/30120035/135247156-20a41e41-2ae0-4cf3-bc60-286da2b6e35e.PNG)

From the above log, the Co-Mixup takes about 1.3s and Vanilla training takes about 0.43s per batch. So the Co-Mixup on ImageNet is slower than Vanilla training about 3 times. This is due to the additional forward-backward pass for saliency calculation and optimization step for Co-Mixup, and reducing the processing time is one of the remained goals. 

If your relative Co-Mixup training time is much slower than my case, then I suspect apex which has many dependency problems. For more dependency-free training code, please refer to [here](https://github.com/snu-mllab/PuzzleMix/tree/master/cutmix), which trains ResNet without apex. 

I hope this helps.

Thanks!
Jang-Hyun

**Comment by minhlong94** [comment]
Hi Jang-Hyun,

Thanks for your reply. My training with 4 Titan Xp takes 2.3s. I also suspect apex is the root cause. I will look more into this, else I will move to the non-dependency training.

As another question, how do you do vanilla training with this apex code? Is it to set `clean_lam = 0`?

Warmly,
Long

**Comment by Janghyun1230** [comment]
Hi, Long

You can do vanilla training by simply comment out Co-Mixup code lines (main_fast_ddp.py L293-310, L315-327).

Best, 
Jang-Hyun
