### ISSUE TITLE
CIFAR100 on preactresnet18 diverges with initial lr of 0.2

### ISSUE THREAD

**Issue by averyma** [snu-mllab/Co-Mixup#6]
Hello,

Thank you again for the quick response on the other issue.
I noticed that even standard training would diverge with initial lr of 0.2 on preactresnet18, with the exact optimization setting described in the paper.

PS: I have not tried it with the exact code from this repo. I took your version of the preactresnet18 and ran with it, and noticed the training divergence.

Did you encounter this issue before?

Thanks,

**Comment by Janghyun1230** [comment]
Hello! 
I didn't encounter that issue when I experimented. Note that we used BCE loss for CIFAR datasets (following the manifold mixup setting). If you use CE loss, then the LR should be tuned.

**Comment by averyma** [comment]
Thank you for pointing it out! I did not even notice it in the manifold mixup codebase.

My understanding is that with BCE loss, it computes a per-class BCE loss over each the classes given an input. 

It seems like a very unconventional approach to me tho, do you have any insight on why BCE loss is used over CE?

I could not find any discussion in the manifold mixup paper either.

**Comment by Janghyun1230** [comment]
To my knowledge, BCE loss is beneficial for multi-class or open set settings where the number of classes is increasing. A recent paper "[ResNet strikes back: An improved training procedure in timm](https://arxiv.org/pdf/2110.00476.pdf)" uses BCE loss when using Mixup and says it improves performance. However, as far as I know, manifold mixup used BCE loss because it is empirically beneficial for their method.
